### PR TITLE
Feat: Added carbon command

### PR DESCRIPTION
**Pull request by nethical6**
Added a fun command that would beautify short codes

### CODE REVIEW

**Comment by iyxan23** [comment]
cool, have you tested it?

**Comment by nethical6** [comment]
@Iyxan23 yep
Works

**Comment by nethical6** [comment]
Screenshot_2021-12-10-11-08-42-51_5a415ff834f6bc153619606941c55eb5

**Comment by iyxan23** [comment]
alright nice

**Pull request merged**
